name: Docs to PDF & HTML

on:
  push:
    branches:
      - main
      - test-action
    paths:
      - 'docs/**.md'
      - 'docs/images/**'

jobs:
  converttopdf:
    name: Build PDF & HTML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Convert Markdown to PDF & HTML
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: docs
          output_dir: tmp/
          images_dir: docs/images/**
          build_html: true

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Refactor artifacts
        run: |
          ls -la
          ls -la tmp
          mkdir artifacts
          mkdir artifacts/pdf
          mkdir artifacts/html
          mv tmp/*.pdf artifacts/pdf/
          mv tmp/*.html artifacts/html/
          ls -la artifacts/pdf
          ls -la artifacts/html
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: artifacts

      - name: Commit and Push artifacts
        run: |
          git add artifacts/
          git status
          git commit -m "Add generated artifacts"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}